### ISSUE TITLE
Week 17 Review Ticket: Rebecca

### ISSUE THREAD

**Issue by Rebecca-123** [shreya-ahujaa/SERA#2]
**Tasks**
- [x] Implemented cayman theme
- [x] Customized navbar/GitHub page
- [x] Running GitHub page locally
   - [x] Fixed URL issue with remote vs local 
      - [_config.yml](https://github.com/shreya-ahujaa/SERA/blob/gh-pages/_config.yml) 
      - [_config_dev.yml](https://github.com/shreya-ahujaa/SERA/blob/gh-pages/_config_dev.yml)
- [x] Deployed backend

**All features below have been tested, and work as intended. No modifications needed.**
**FRQ Related**
**[Link to frontend code: HTML/CSS/JS](https://rebecca-123.github.io/fastpage-CSA/frq4/frontend)**
1. [Light Board](https://shreya-ahujaa.github.io/SERA/frqs/frq4)
2. [Word/Text Counter](https://shreya-ahujaa.github.io/SERA/frqs/sentences)
- [x] Generate randomized info on a single light bulb
   - [x] Create button to allow for new bulb replacing old one
- [x] Generate table of randomized light bulb info 
   - [x] Create a button to add another light bulb
- [x] Randomized board of colors
   - [x] Same board, but with effects (function)
   - [x] Same board, specific sizing (user input)
   - Fetch with GET request
- [x] Custom size checkerboard
   - If new size entered, old checkerboard replaced (jQuery) 
- [x] Gradients 
   - [x] Red 
   - [x] Green
   - [x] Blue
- [x] Word and character counter
   - Fetch with POST

**Additional Backend Work for FRQ 4**
- [Code](https://github.com/Rebecca-123/SERA_spring/tree/main/src/main/java/com/nighthawk/team_backend/mvc/lightboard)
   - Additional API endpoints
   - Additional subclass for checkerboard lights
   - Additional Light constructor with arguments
