### ISSUE TITLE
Rebecca: Final PBL

### ISSUE THREAD

**Issue by rebecca-123** [shreya-ahujaa/SERA#24]
### **Total: 19.5/20**

| Criteria | Self-Grade | P1 | P2 | Avg |
|----------------------------------------------------------|--------------------|------------|-------------|-----------------|
| **N@tM** | **5/5** | **5/5** | **5/5**| **5/5**|
| Individual Attendance, Capture the Moment<br><img width="230" alt="image" src="https://user-images.githubusercontent.com/58576326/221653022-f8953934-10d1-4979-8f2c-89e474cfffe4.png"><br><img width="279" alt="image" src="https://user-images.githubusercontent.com/58576326/221662738-3c364b6d-fed9-4b9d-8b1e-dd0980d4cca1.png"> | 2/2 | 2/2 | 2/2| 2/2|
|Team Presentation to Teacher<br> | 3/3 | 3/3 | 3/3 | 3/3 |     
| | | | | |
| **Live Review**| **10/10**| **10/10** | **10/10** | **10/10** |
| Individual Score for Runtime (binary criteria below) | 5/5| 5/5 | 5/5 | 5/5|
| Project quality, running cross domain and no crashes on FE to BE with these reviews | 1/1 | 1/1 | 1/1 | 1/1|
| UI contains inputs that are validated for garbage, data cleaned (ie validate DOB or Password)<br> - [Code](https://raw.githubusercontent.com/shreya-ahujaa/SERA/gh-pages/signup.md)<br>- Validating password (retype and complexity requirements)| 1/1 | 1/1 | 1/1 | 1/1 |
|UI contains actions for Create, Read<br>- [Create](https://shreya-ahujaa.github.io/SERA/signup)<br>- [Read](https://shreya-ahujaa.github.io/SERA/clubs)| 1/1 | 1/1 | 1/1 | 1/1 |
|UI contains actions for Update, Delete<br>- [Update](https://shreya-ahujaa.github.io/SERA/update)<br>- [Delete](https://shreya-ahujaa.github.io/SERA/delete)| 1/1 | 1/1 | 1/1 | 1/1|
|JWT is guarding at least two features, demonstration of cookies<br>- [antMatchers](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/SecurityConfig.java#L68-L70)<br>- Guards update and delete methods| 1/1 | 1/1 | 1/1| 1/1|
| Individual Score for Code Review (binary criteria below)<br> [API Controller](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/mvc/database/club/ClubApiController.java) |5/5 |5/5 | 5/5 | 5/5 |
|Project quality, observation of comments in every function, class, or method reviewed | 1/1 |1/1| 1/1 | 1/1 |
| BE contains and API that shows that it handles error conditions (ie duplicate user id) | 1/1 |1/1| 1/1 | 1/1 |
| BE contains support for GET and POST methods |1/1 |1/1| 1/1 | 1/1 |
| BE contains a database that supports Create, Read  |1/1 |1/1| 1/1 | 1/1 |
| BE contains a database that supports Update, Delete  |1/1 |1/1| 1/1 | 1/1 |
| | | | | |
| **Silent Review** |**4.5/5** |**4.5/5** |**4.5/5** | **4.5/5** |
| Team | 1.5/3 |1.5/3  |1.5/3  | 1.5/3 |
| Individual | 3/2|3/2 |3/2 | 3/2|
| Individual Review Ticket  | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 |
| Runtime Links  | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 |
| Technical Accomplishments  | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 |
| Blog, Guides for review  | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 |
| Meeting full stack and backend objectives  | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 |
| GitHub analytics  | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 | 0.5/0.5 |
| **Total** | **19.5/20** | **19.5/20** | **19.5/20**| **19.5/20**|

### Review Tickets
- [x] [Nav Bar and Home Page](https://github.com/shreya-ahujaa/SERA/issues/16)
- [x] [Tangible Artifacts: Project Development Week 3](https://github.com/shreya-ahujaa/SERA/issues/20)
- [x] [Full-Stack Feature](https://github.com/shreya-ahujaa/SERA/issues/12)

### Runtime Links
- [Frontend](https://shreya-ahujaa.github.io/SERA/)
- [Backend](https://rebeccaaa.tk)

### Technical Accomplishments
- [X] [Blog, Guides for review](https://rebecca-123.github.io/fastpage-CSA/club-compass)

### [GitHub Analytics](https://github.com/Rebecca-123)
- [FE Analytics](https://github.com/shreya-ahujaa/SERA/graphs/contributors)
- [FE Commits](https://github.com/shreya-ahujaa/SERA/commits?author=Rebecca-123)
- [BE Analytics](https://github.com/Rebecca-123/SERA_spring/graphs/contributors)
- [BE Commits](https://github.com/Rebecca-123/SERA_spring/commits?author=Rebecca-123)

**Comment by PranaviInukurti** [comment]
**Score: 19.5/20**
- N@TM Stufff (5/5)
- Individual Runtime (5/5)
- Individual Code Review (5/5)
- Team Review Ticket (1.5/3)
- don't have video
- READ.me missing
- no blogging
- Individual Review Ticket (3/2)

**Comment by xiaoa0** [comment]
Score: 19.5/20
- N@TM: 5/5
- Individual runtime: 5/5
- Individual code review: 5/5
- Team review ticket: 1.5/3
- No video, readme, or blog
- Individual review ticket: 3/2
